#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
from optparse import OptionParser

from chroot import Chroot, ChrootError

def main(argv):
    usage = "%prog [OPTION] NEWROOT [COMMAND [ARG]...]"
    version = "%prog alpha"
    parser = OptionParser(usage=usage, version=version)

    for ind, arg in enumerate(argv):
        if not arg.startswith("--"):
            opts = parser.parse_args(argv[:ind])[0]
            ndir = argv[ind]
            cmds = argv[ind + 1:]
            break
    else:
        parser.print_help()
        sys.exit(1)

    try:
        ech = Chroot(ndir, ' '.join(cmds))
        ech.chroot()
    except ChrootError, err:
        print "echroot: %s" % err
        sys.exit(1)
    else:
        exit(0)

if __name__ == "__main__":
    try:
        main(sys.argv[1:])
    except KeyboardInterrupt, e:
        print >> sys.stderr, "\n\nExiting on user cancel."
        sys.exit(1)
